#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED


#define TAILLE_BLOC  34


enum{HAUT,BAS,GAUCHE,DROITE};
enum{VIDE,MUR,LINK,ROCHER,LINKD,
BOMBE,BOMBECENTRE5,BOMBEBAS5,BOMBEHAUT5,BOMBEDROIT5,BOMBEGAUCHE5,
BOMBEROUGE};




#endif // CONSTANTES_H_INCLUDED
